### PR TITLE
Changed Delegate to be bower compatible, out of the gate

### PR DESCRIPTION
**Pull request by blainekasten**
This changes the delegate library to be UMD Compliant, and bower ready out of the gate.

### CODE REVIEW

**Comment by kaelig** [comment]
Ping @matthew-andrews

**Comment by matthew-andrews** [comment]
@kaelig sorry i missed this & away now… seems ok to me do you want to take over merge & release?

**Comment by kaelig** [comment]
Sorry, not feeling very comfortable merging code that I don't understand fully…

**Comment by pfraces** [comment]
@matthew-andrews: Any plans for merging this?
IMO it is useless to have a package in the bower registry which needs to be browserified

**Comment by blainekasten** [comment]
I'm closing this due to inactivity, and I no longer need this. If someone else needs this they can use this PR as a starting point (or not).

**Pull request closed without merging**
