### PR TITLE
Change name to ftdomdelegate so we stop having two versions of the sa…

### PR DESCRIPTION
**Pull request by AlbertoElias**
…me module

### CODE REVIEW

**Comment by AlbertoElias** [comment]
@triblondon I don't have access to ftlbas stuff

**Comment by matthew-andrews** [comment]
this'll need to be a major version ^^

**Comment by AlbertoElias** [comment]
Really? Why is that?

**Comment by matthew-andrews** [comment]
anyone pulling this module in with bower and commonjs will be doing `require('dom-delegate')` and that'll suddenly break

**Comment by matthew-andrews** [comment]
unless it doesn't and it won't… but i think so…

**Comment by AlbertoElias** [comment]
It's being requested as `ftdomdelegate` though https://github.com/Financial-Times/o-header/blob/master/src/js/Header.js#L3

**Comment by AlbertoElias** [comment]
Oh, right, I think I understand what's going on. So if someone ran `bower install ftdomdelegate` they would get the one from the Origami registry, but if they ran `bower install dom-delegate` they would get the one in the Bower registry and not [Wilson's one](https://github.com/wilsonpage/dom-delegate). In that case, yes, it would need to be a major release

**Comment by JakeChampion** [comment]
closed by #93

**Pull request closed without merging**
